# Generated by Django 3.1.2 on 2020-10-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201024_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
