# Generated by Django 3.1.2 on 2020-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201026_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='play_status',
            field=models.BooleanField(default=False),
        ),
    ]
