# Generated by Django 3.1.2 on 2020-11-12 19:42

import boards.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('south', boards.fields.ListField()),
                ('north', boards.fields.ListField()),
                ('east', boards.fields.ListField()),
                ('west', boards.fields.ListField()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('table', models.PositiveIntegerField()),
                ('south_player', models.CharField(max_length=50)),
                ('north_player', models.CharField(max_length=50)),
                ('east_player', models.CharField(max_length=50)),
                ('west_player', models.CharField(max_length=50)),
                ('bidding', boards.fields.ListField()),
                ('tricks', boards.fields.ListField()),
                ('contract', models.CharField(max_length=10)),
                ('final_result', models.CharField(max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='boards.hand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
