# Generated by Django 3.1.2 on 2020-11-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='vulnerableEW',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='vulnerableNS',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hand',
            name='unique_id',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
